name: World_BQ_Score_Automation

on:
  #schedule:
    # Trigger the action every day at 7:00 PM IST (13:30 PM UTC)
    #- cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  Fetch-world-stock-bigquery-score:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Git LFS
    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install
        
    # Step 4: Set up Google Sheets Authentication
    - name: Set Up Google Sheets Authentication
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$SERVICE_ACCOUNT_JSON" > service_account.json

    # Step 5: Configure Git
    - name: Set up Git
      run: |
        git config --global user.name "Aravinthkumar World BQ"
        git config --global user.email "aravinthkumarj1@gmail.com"

    # Step 6: Check if today is Saturday or Sunday
    - name: Skip Saturdays and Sundays
      id: check_day
      run: |
        DAY_OF_WEEK=$(date +%u) # 1=Monday, 7=Sunday
        if [[ "$DAY_OF_WEEK" -eq 6 || "$DAY_OF_WEEK" -eq 7 ]]; then
          echo "continue=true" >> $GITHUB_ENV
        else
          echo "continue=true" >> $GITHUB_ENV
        fi

    # Step 7: Run the BSE stock data update script
    - name: Run BSE stock data BigQuery update script
      if: ${{ env.continue == 'true' }}
      run: |
        python scripts/World_BQ_Score_Master.py

    # Step 8: Authenticate and Push Changes
    - name: Authenticate and Push Changes
      if: ${{ env.continue == 'true' }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        #git remote set-url world https://x-access-token:${GH_PAT}@github.com/greenteamz/Daily_NSE_Stock_Fetch.git
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/greenteamz/world_stock_master.git
        
        # Add files that may go beyond 100MB and push them
        git config --global lfs.required true  # Git LFS (Large File Storage) configuration
        
        git status
        git add scripts/* .github/* WORLD_Test/*
        
        # Check for large files and ensure they are handled with Git LFS
        git lfs track "*.csv" "*.xls" "*.xlsx" "*.log"  # Adjust based on your file types

        git commit -m "$(date) World stock update"
        git push origin main --force
        #git push world  main --force
